### ISSUE TITLE
Ability to perform a value conversion to a target type

### ISSUE THREAD

**Issue by rjbaucells** [josdejong/typed-function#1]
While working on some of the algorithms in [mathjs](https://github.com/josdejong/mathjs) I got to the necessity of converting a given value to a target type. This feature will allow the implementation of some performance enhancements in mathjs. The specific case is something like:
- Processing a Matrix that contain values of a given type (`Complex` as an example)
- Algorithm require checking that a value of the Matrix type is different than zero
- A good performance enhancement will be obtaining the `equal(x,y)` signature that matches the Matrix data type (`equal(Complex, Complex)`).

```
var type = 'Complex'; // Matrix datatype
...
var complexEqual = equal.signatures[type + ',' + type];
...
var zero = typed.convert(0, type);
...
if (complexEqual(value, zero)) {
}
```

Just a feature that will be nice and will have a direct impact on mathjs.

**Comment by josdejong** [comment]
So you mean to expose a utility function `convert(value, type)`, that makes sense, thanks for the idea.

**Comment by rjbaucells** [comment]
Yes, exactly. The same way  a utility function would be good to find the method signature that matches a set of parameter types to avoid looking at the `signature` object definition (that could change in the future).

**Comment by josdejong** [comment]
The comma separated parameter signatures (like `Complex,Complex`) should never change, but I agree it would be a good idea to have a util function which hides this for you. Do you mean a util function where you pass the argument types like `['number', 'number']`, or based on "sample" arguments like `[2, 3]`?

Addressing a specific signature is a bit verbose right now. It would be nice if we could find a more compact way for this.

**Comment by rjbaucells** [comment]
The need I have is based on types, at this point I have not processed the specific values I just need to get a handle to the function I will invoke later that I know the parameter types of.

**Comment by josdejong** [comment]
I've implemented utility functions `convert` and `find`. The latter is very limited right now, it only recognizes exact matching signatures, but this should be enough for now. So your initial code example can be changed to:

``` js
var type = 'Complex'; // Matrix datatype
...
var complexEqual = typed.find(equal, [type, type]); 
...
var zero = typed.convert(0, type);
...
if (complexEqual(value, zero)) {
  ...
}
```

**Comment by rjbaucells** [comment]
Perfect, this is exactly what I needed.
