### ISSUE TITLE
add an esmodule build

### ISSUE THREAD

**Issue by jauco** [josdejong/typed-function#104]
Would you be open to a PR that adds an esmodule build next to normal and the minified version (typed-function.mjs with a module entry in the package.json)?

Since the whole code is one module, my suggested approach would be to generate typed-function.js from the esmodule version by wrapping it in the IIFE. If you prefer a different solution, just let me know.

**Comment by josdejong** [comment]
Hi Jauco, yes that would be great! Thanks for your offer.

Your approach makes sense: change the source code into an ES module, and from that generate a minified UMD bundle. It may also be a nice to take this opportunity to remove the minified bundle from the repo, and neatly split into an `src` and `dist` folder.

**Comment by josdejong** [comment]
We recently had big changes in `typed-function` (mostly implemented by @gwhitney). This breaks the still open PR with a refactoring to ES modules. I would like to create a new PR with this conversion, and have some thoughts:

- Having an npm package with both ES, CommonJS, UMD, etc easily gives troubles with the various package managers
- The future is ES modules
- Maybe this is the time to do a bold step and go ES module only?

We would still need to transpile the code with babel so the output JS is ES5 or ES6 so we will not accidentally use new JS features that are not yet available in all browsers.

**Comment by josdejong** [comment]
I created a new PR refactoring the code to ES modules: #160

**Comment by josdejong** [comment]
I've now merged the PR and published `typed-function@4.0.0`. see https://github.com/josdejong/typed-function/pull/160#issuecomment-1222314046 for details.

**Comment by josdejong** [comment]
Hmm. I should have known, but the ES modules gives issues with mathjs since mathjs outputs a CommonJS version of the library too. Let me see tomorrow if that is fixable, and if not I can generate an UMD version of `typed-function` anyway.

**Comment by josdejong** [comment]
Ok that wasn't very well thought through of mine 😅 . Because mathjs outputs a CommonJS version, we still need it's dependencies (like typed-function) to have CommonJS version too. It's a bit of a bridge-too-far to drop CommonJS support from mathjs right now. I would love to get rid of all the legacy though.

In `typed-function@4.1.0` I'm outputting both ESM code and UMD code (which includes CJS support) now, so all is good now and backward compatible.
