### ISSUE TITLE
Function length

### ISSUE THREAD

**Issue by Hypercubed** [josdejong/typed-function#13]
Hello!

I just came back to an old project that was using typed-function internally and tried to update to the latest version.  Unfortunately, I've found that the new version generates all typed functions as a function with a length of two.  I was relying on the length being equal to the length of the signatures (or max of).  Was this a conscious breaking change?  Any reason we can no longer set the length to the max of the signature functions?

**Comment by Hypercubed** [comment]
Possible fix: https://github.com/Hypercubed/typed-function/tree/fix/function-lengths

**Comment by josdejong** [comment]
Generally, a typed-function can have multiple signature each with a different number of arguments. A safe way to check the number of arguments would be to loop over `myTypedFunction.signatures`, split each of the signatures and count the arguments., and then calculate the maximum from that.

The new version v1 has huge performance improvements over v0. This is largely achieved by putting a fast, happy-path evaluation for 0, 1, or 2 arguments and up to 6 signatures around the more slow and generic function evaluating for any signature:

https://github.com/josdejong/typed-function/blob/aff577b45f4df8bf641cfc128b9e386d31b90809/typed-function.js#L1080-L1093

**Comment by Hypercubed** [comment]
Sound like it was not an explicit feature in v0... but I found it useful.  Please consider #17
