### ISSUE TITLE
Possible feature: client-supplied typing function

### ISSUE THREAD

**Issue by gwhitney** [josdejong/typed-function#139]
typed-function could optionally allow its clients to supply a typing function compatible with the type system they had set up. This would be a function that would take any entity and return a nonempty string, the "computed type" of the entity, or a falsy value, meaning "I couldn't tell". Then dispatch would first check if all of the arguments had computed types, and if so, construct the signature consisting of those types in order, and if that signature is present in the typed-function, immediately dispatch to it. Only if this process failed would it go through its standard check-all-the-predicates dispatch mechanism.

It would be up to the client to ensure that this shortcut would never subvert the dispatch they want, based on the type system they have collated.

This would work well for types that are quickly recognizable and disjoint from all other types. For example, if their type system has a type 'string' that corresponds exactly to the native type and it has no other types that overlap with this (and say the rest of the type system is complicated), the typing function could be `x => typeof x === 'string' ? 'string' : false`

The default typing function if not otherwise supplied by the client _could_ be
```
x => x === null ? 'null' ? typeof x === 'undefined' ? 'undefined' : false
```
but this is sufficiently unlikely to be useful that it would not "pay for itself", so I think the default would be no typing function.

**Comment by josdejong** [comment]
It's an interesting idea, thanks for sharing. It can be really powerful to be able to determine your own type checking. I'm not sure if/how we should implement it. I expect it would be some "preprocessing" step, and it will not work with conversions and things like that.

It may be that it is easiest to not integrate something like this in typed-function itself, but instead just create a wrapper function if you need something like this:

```js
function myFunction(arg1, arg2) {
  if (myFastTest(arg1, arg2)) {
    return ...
  } 
  return typed({ ...signatures... })
}
```
A downside of this may be that `myFunction` is not a typed-function itself now.

**Comment by gwhitney** [comment]
Ar this point this seems only like something that might be included in a roadmap for the future, so perhaps it's not worth much further discussion now. The concept was something that would speed dispatch across many typed functions in the same instance. If you have a single function you want to be fast, you're likely not going to make it a typed-function anyway.

**Comment by josdejong** [comment]
Yes makes sense. Ok let's close this topic for now. We can always find it back and reopen when a good use case arises. Thanks for your inputs 👍

**Comment by gwhitney** [comment]
OK, in terms of use cases, I took a look at mathjs, which is presumably the most major instance of typed-function. Given the type hierarchies there, with many subclasses of Node and a few subclasses of Matrix, something like this would only work if typed-function were extended to understand subclasses. So I think this issue need only be reconsidered if/when something along the lines of #140 is implemented.

**Comment by josdejong** [comment]
Yes maybe. I'm not sure though how `typed-function` could do something at all when (some) types are defined as a dynamic test function and not a static string containing the type. Good to keep this in mind at least 👍

**Comment by gwhitney** [comment]
Not to continue the conversation too much in a closed issue (so feel free to not respond ;) but the motivating example of a typing function is
```
function naturalType (entity) {
  const t = typeof entity
  if (t !== 'object') return t
  if (entity === null) return 'null'
  if (entity.constructor && entity.constructor.name) return entity.constructor.name
  return 'object'
}
```
And this would definitely do something decent on mathjs, but I think would currently lead it astray on (for example) functions on Nodes, which don't mostly take 'AccessorNode' or 'ConditionalNode' arguments, which would be the natural types this function would return, but instead just take Node arguments -- the functions mostly don't care what kind of node.

But just to make sure my concept was clear, the type hierarchy and type names and test functions would remain completely identical with a feature like this, and they would define the actual semantics of the types. The typing function would just be a dispatch speedup mechanism: compute an "obvious type" directly from the values when possible, and then see if the signature called for by all the obvious types is there, and if so, call it: no need to iterate through a list of test functions; but if that doesn't work, fall back to the slower "standard dispatch."

In this scenario it would be up to the type hierarchy designer to ensure that the typing function was consistent with the type hierarchy in the sense that if a signature was found the "quick way", it would be the one that would be the best match in the "standard way." That's what I am worried about guaranteeing without typed-function knowing about subtype relationships. Basically, in the current type system, for safety currently the type of a value computed by the typing function better not have any overlapping types (that are not supertypes of it). Not sure how easy it would be to guarantee that in mathjs. Hence, my being fine with leaving this for a dim and unlikely-to-be-reached future.

**Comment by josdejong** [comment]
Ah, I get what you mean. 

So the current approach basically is: iterate over each of the signatures one by one, and test one by one whether the arguments match the expected type. There is a "fast, specialized" version of these testing which triggers when a function has max 2 arguments and max 6 signatures, but it's still following the same approach.

Your idea is to first determine the type of the arguments, and if they are unique, lookup if there is a matching signature. That could be done with a map or nested map or something smart.

It's definitely an interesting experiment to try a different way of dispatching. It can be a good idea, though we should heavily benchmark a new approach to see if it is really faster in practice. Whether it is faster depends on a lot of things: 

- compare performance with many or only a few signatures (your idea can be faster when having many signatures). 
- compare with a few vs many arguments, and dealing with variable arguments
- compare what is faster when having many conversions defined vs only a few conversions
- what way of testing is actually fastest? In browser engines, it may be that executing these type tests is just very fast. I have no idea how it would compare to generating strings with the type names, maybe concatenating these strings, and then looking it up in a map. 

JavaScript engines can do crazy things with optimization, so we really need real-world benchmarks and not trust our own assumptions. A general rule I learned from the guy that created Lodash is: to optimize performance, prevent creating stuff like intermediate objects, arrays, strings (initializing memory and garbage collection is slow). And write predictable functions that have strict input/output so the JS engine can recognize that and optimize for that.
