### ISSUE TITLE
Passing null to a type-function causes error...

### ISSUE THREAD

**Issue by Hypercubed** [josdejong/typed-function#15]
The following causes an error:

```
var typed = require("typed-function")

var fn1 = typed({
  'Object': function (a) {
    return 'a is a Object';
  }
});

console.log(fn1(null));
```

indise the "Object" check since `typeof null === 'object'` but `x.constructor` throws.

**Comment by josdejong** [comment]
Ouch! That is one of these classic JavaScript pitfalls :astonished:  

Fixed via https://github.com/josdejong/typed-function/commit/09b969f467838d8683a067d32d5a3f81e4b10cf9 (not yet published)
