### ISSUE TITLE
typed.addType() fails if there is no Object type

### ISSUE THREAD

**Issue by gwhitney** [josdejong/typed-function#155]
To reproduce:
```
import typed from 'typed-function'

const pocomath_universe = typed.create()
pocomath_universe.clear()
pocomath_universe.addType({name: 'number', test: n => typeof n === 'number'})
```

This is my fault: I thought addType should reproduce the behavior from v2 of inserting before Object, but overlooked softening that to inserting before 'any' if there is no Object type. I do not think the above code should throw an error, although it can be worked around by supplying the 'beforeObjectTest = false' parameter.

**Comment by josdejong** [comment]
Thanks for reporting 👍
