### ISSUE TITLE
Suggestion about the homepage documentation

### ISSUE THREAD

**Issue by dvd101x** [josdejong/typed-function#165]
Hello all, awesome library!

I was reading into the docs: [Methods of the typed package](https://github.com/josdejong/typed-function#methods-of-the-typed-package)

While trying to add a single type with `typed.addType()` before the `'Array'` type I saw this reference in the docs.

`typed.addTypes(types: TypeDef[] [, before = 'any']): void`

Thus I changed my code to `typed.addTypes()` even though I only needed one.

After a while I found out the it also seemed to work for a single type, but didn't find that reference in the documentation.

Maybe something like this could be helpful.

```js
typed.addType({
  name: 'Person',
  test: function (x) {
    return x && x.isPerson === true;
  },
  before: 'Matrix' // optional
});
```

Maybe I missed it, it's implied that it should also work or I'm using it wrong.

I'm submitting this for review just in case there are any actions necessary.

**Comment by dvd101x** [comment]
I'm sorry, I was trying to replicate the "issue" and I can't, I will close it until I have a better understanding.

**Comment by josdejong** [comment]
👍 . The two methods `addType` and `addTypes` are indeed not the same, `addType` has a special optional argument `beforeObjectTest` which is a boolean, whereas `addTypes` is more flexible and has an optional `before`.
