### ISSUE TITLE
Please add MIT to package.json license field

### ISSUE THREAD

**Issue by ronaldcurtis** [josdejong/typed-function#168]
Hi, thanks for your great library 🙏 

Just wondering if you could add `"license": "MIT"` to your `package.json` field. I know there is already a `LICENSE` file, but having it in `package.json` will also help with tools such as https://github.com/jslicense/licensee.js, https://github.com/davglass/license-checker, and so forth.

**Comment by josdejong** [comment]
Thanks Ronnie :)

I've published `v4.1.1` having the license field in the package.json file.
