### ISSUE TITLE
According to Rollup, typed-function does not export

### ISSUE THREAD

**Issue by EliasHasle** [josdejong/typed-function#18]
I am trying to bundle (part of, or whole) mathjs with my project, but it fails, telling me that typed-function does not export `default`. Mentioned in https://github.com/josdejong/mathjs/issues/1232

Narrowing down the problem by creating a new package:
package.json:
````
{
	"name": "typedFunction",
	"scripts": {
		"build": "rollup -c"
	},
	"dependencies": {
		"mathjs": "^6.0.3"
	},
	"devDependencies": {
		"rollup-plugin-node-resolve": "^5.2.0"
	}
}
````

rollup.config.js:
````
import resolve from "rollup-plugin-node-resolve"

export default {
	input: "main.js",
	output: {
		file: "typedFunction.js",
		format: "umd",
		name: "typedFunction",
	},
	plugins: [
		resolve(),
	],
}
````

main.js:
````
import typedFunction from "typed-function";
export {typedFunction};
````

`> npm run build`

Output:
````
PS C:\Users\XXXXX\GitHub\implementations-spring-2019\temp> npm run build

> typedFunction@ build C:\Users\XXXXX\GitHub\implementations-spring-2019\temp
> rollup -c


main.js → typedFunction.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules\typed-function\typed-function.js
21:     root.typed = factory();
22:   }
23: }(this, function () {
      ^
24:
25:   function ok () {
(!) Import of non-existent export
main.js
1: import typedFunction from "typed-function";
          ^
2: export {typedFunction};
[!] Error: 'default' is not exported by node_modules\typed-function\typed-function.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-
main.js (1:7)
1: import typedFunction from "typed-function";
          ^
2: export {typedFunction};
Error: 'default' is not exported by node_modules\typed-function\typed-function.js
    at error (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:9408:30)
    at Module.error (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:13347:9)
    at handleMissingExport (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:13269:21)
    at Module.traceVariable (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:13656:17)
    at Module.getVariableForExportName (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:13472:25)
    at Module.includeAllExports (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:13499:35)
    at Promise.all.then (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:16769:24)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typedFunction@ build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typedFunction@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXXX\AppData\Roaming\npm-cache\_logs\2019-07-23T08_26_39_227Z-debug.log
````

It looks like the error is connected to the warning about `this` being `undefined`, but I don't know for sure.

**Comment by EliasHasle** [comment]
OK. Referring https://github.com/rollup/rollup/issues/578, applying the commonjs plugin solved the problem. I thought mathjs was now using ES6 modules throughout.

**Comment by josdejong** [comment]
Probably the same as #1232. Thanks for the detailed description, will try to reproduce and see if we can do anything about this in the mathjs lib.

**Comment by josdejong** [comment]
? o wait. Confused why did you close the issue already?

mathjs is indeed ES6, typed-function is still ES5 and delivers a UMD libray.

**Comment by EliasHasle** [comment]
I closed it because 1. I had solved my usage problem, and 2. I thought it was normal behavior from typed-function, but using an incompatible import from mathjs. If, however, typed-function is supposed to be compatible with import statements, then it is indeed an error here too.

**Comment by josdejong** [comment]
> If, however, typed-function is supposed to be compatible with import statements, then it is indeed an error here too.

the `typed-function` export should be compatible with all sorts of import statements, it's a generic UMD export format. If it doesn't work we should look into it.

**Comment by EliasHasle** [comment]
Quote from https://salomvary.com/es6-modules-in-browsers.html regarding usage in browsers:

> Using UMD modules with import is not possible either. Browsers throw a SyntaxError when attempting to parse a file as an ES6 module if it contains no export definition.

However, Rollup provides conversion through [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs), which I have incidentally not included in the above config. Running with it worked as expected:

```
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";

export default {
	input: "main.js",
	output: {
		file: "typedFunction.js",
		format: "umd",
		name: "typedFunction",
	},
	plugins: [
		resolve(),
		commonjs(),
	],
}
```

So then the problem may be in the build configuration for mathjs (josdejong/mathjs#1232), rather than in that for typed-function. I recommend checking the config of rollup-plugin-commonjs and possible interfering plugins.

**Comment by josdejong** [comment]
That makes sense. Thanks for the update Elias.
