### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by bitwiseman** [josdejong/typed-function#4]
This looks like a project that is of reasonable size and stability.  What additional features are needed to declare it ready for a 1.0 release?

**Comment by bitwiseman** [comment]
Okay, so... reading all of the read me is a good idea.

**Comment by josdejong** [comment]
Yes what's there is stable and already put to the test in math.js v2 (which is not yet released), so we could call it a `v1`. I think the moment we release math.js `v2` we can also release `v1` of `typed-function`, but there are still a few rough edges I would like to improve. The roadmap is a rough idea on what I had in mind for a first "feature complete" library.
