### ISSUE TITLE
Add type: `undefined`

### ISSUE THREAD

**Issue by bitwiseman** [josdejong/typed-function#5]
`undefined` is not the same as `null` in javascript. 
For example, if you don't pass an argument, it will be `undefined`.  Also `{}['notset']` returns `undefined`.

**Comment by josdejong** [comment]
Thanks. `typed-function` already contains support for `undefined` ([see code](https://github.com/josdejong/typed-function/blob/master/typed-function.js#L1088)), but I see it was missing from the docs.

If you don't pass an argument, typed-function with throw an error "Too few arguments".

**Comment by gwhitney** [comment]
Closing, as the feature the original poster wanted is present in typed-function.
