### ISSUE TITLE
[Design question] Why don't typed functions inherit the name of untyped functions?

### ISSUE THREAD

**Issue by cshaa** [josdejong/typed-function#90]
There is [a unit test](https://github.com/josdejong/typed-function/blob/develop/test/construction.test.js#L61) that specifically makes sure that the result of the following code will be an empty string:
```javascript
const haha =
typed({
  'string': function haha(s){ return 'haha' },
  'number': function haha(n) { return Array(n+1).join('ha') }
});

haha.name
```
I understand how this happens in the code, the overload [`typed(Object)`](https://github.com/josdejong/typed-function/blob/develop/typed-function.js#L1324) uses the function [`getName(fns)`](https://github.com/josdejong/typed-function/blob/develop/typed-function.js#L1256) to infer the name, but this function purposefully ignores non-typed functions (see [line 1263](https://github.com/josdejong/typed-function/blob/develop/typed-function.js#L1263)).

However, I don't understand the UX of this decision. Why was it designed this way?

**Comment by josdejong** [comment]
The reason was that there where troubles with relying on the name of plain JavaScript functions, most importantly because function names can be mangled when minifying JavaScript code, so in development all looks fine, but in production you suddenly see weird error like "Function uY expects a number instead of a string".

**Comment by cshaa** [comment]
Thanks for the clear and concise explanation!

**Comment by josdejong** [comment]
👍 

it sounds easy now but I had to figure this out the hard way 😅
